### ISSUE TITLE
Supermarine final bugs

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina#316]
- [x] Long config items in dropdowns look funny:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/17623856/49199038-fa36b000-f363-11e8-86a4-c43f5024171b.png">

- [x] There is a funny little white box under the "Change Status" button on tool info and "Change Role" on user info
- [x] There doesn't seem to be a check for failure on user creation and editing
- [x] When adding/updating a tool, the client code turns the price into null if the price is > 5 digits long (including cents)

**Comment by MajorT0m** [comment]
- [ ] Noticed that the first time I logged in and tried creating a user, that on the final step of creating a user the user block only showed "UU". When I clicked "Done", I was returned to the user list, but my new user wasn't there. This continued until on that final step I hovered over the "UU" block. Since then, the users have been successfully adding, and the "UU" only appears for a second before being replaced with the initials. Haven't been able to recreate this, even after clearing browsing data, and retrying with a new administrator.

**Comment by Jbcampbe** [comment]
- [ ] fix `between 1950 and 2019` issue on new-tool page
- [ ] Getting a failure message when adding a tool that is specifically $2.22, $1.11, or $4.44 in value. But $3.33 worked. However, after a failure due to one of the 3 above values, changing to another valid value resulted in a failure message as well.
- [ ] missing `decomission`, `recomission` and `maintenance` filters on history
- [ ] make sure all updates are displaying on history detail view

**Comment by Jbcampbe** [comment]
- [ ] decommissioned tools can still sometimes show up in the search results if they are cached

**Comment by Jbcampbe** [comment]
- [ ] editing tools has an issue on desktop. Change status is greyed out and `The specified value "$ 0.00" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?` shows up in the console. Clicking change status causes a bunch of things to blink

**Comment by Jbcampbe** [comment]
> * [ ]  Noticed that the first time I logged in and tried creating a user, that on the final step of creating a user the user block only showed "UU". When I clicked "Done", I was returned to the user list, but my new user wasn't there. This continued until on that final step I hovered over the "UU" block. Since then, the users have been successfully adding, and the "UU" only appears for a second before being replaced with the initials. Haven't been able to recreate this, even after clearing browsing data, and retrying with a new administrator.
> 
> Mabye related is the fact that we don't have any error handling on the add user (maybe update user too?) page
> 
> I was able to reproduce that bug by using a really long name. Reproduced it twice. Try using:
> First name: Sir Englesburg Saxton Subrington Hasselford Hundruffle Garthwright
> Last name: Langfordlongshanks-Spinthingtonweaselsnoutsalsbury
> Email: [elangford@thisisthelongestandstrangestdomainever.com](mailto:elangford@thisisthelongestandstrangestdomainever.com)
> 
> Hmmmmm, but I also get it when I do short names sometimes....maybe we can walk through this one at some point, if you guys try to fix it. I thought I narrowed down the issue, but it seems inconsistent.

Yeah I'm guessing this is because we aren't doing any failure checks. Also the ui doesn't wait for the request to finish before moving to the next page so the `UU` is actually `Undefined Undefined`: ) Should be fixed by adding some error handling and waiting for the request to finish before displaying that page
